export enum LandscapeType {
    BLUE_PLAINS = "BLUE PLAINS",
    CORNFIELDS = "CORNFIELDS",
    USELESS_SWAMP = "USELESS SWAMP",
    SANDYLANDS = "SANDYLANDS",
    NICELANDS = "NICELANDS",
    RAINBOW = "RAINBOW",
    ICY_LANDS = "ICY_LANDS"
}